### ISSUE TITLE
Team 18 Review VnVPlan: Usability Survey

### ISSUE THREAD

**Issue by billsong0407** [RutheniumVI/UnderTree#21]
The scales used in the usability survey are ambiguous. 
For example: On a scale of 1 to 10, how responsive would you say the system is?
Does a 10 indicate very responsive or very unresponsive? Thus, some indicators should be provided on both end of the scale (where 1 being unresponsive and 10 being responsive, etc).

**Comment by qureshe00** [comment]
Updated in VnV plan
