### ISSUE TITLE
Team18 Review: More details on the verification plans

### ISSUE THREAD

**Issue by marlon4dashen** [RutheniumVI/UnderTree#22]
Hi, all! It is a great VnV plan overall. But I noticed that the verification plans (part4) lack details.  First of all, in 4.1 Verification and Validation Team, the role and responsibility of each member are not explicitly defined. For example, who will be responsible for backend testing and who will be for frontend testing, etc. Additionally, in sections 4.2 and 4.3, it's great that you mentioned to verify through peer reviews and feedback. However, the approach is not specified. What's the structure of the reviews? Can it be ad hoc, or even better structured?  One suggestion is to also use a checklist in the design verification plan by asking architectural questions regarding your designs.

**Comment by qureshe00** [comment]
Updated sections 4.1, 4.2, 4.3
