### ISSUE TITLE
Team 18 Review (VnV Plan): Tests for Non-Functional Requirements

### ISSUE THREAD

**Issue by Niu0351** [RutheniumVI/UnderTree#30]
There are some survey questions in non-functional requirements, but the answers provided by users can be better measured by more detailed surveys. The overall feedback provided by users would be augmented by asking more than one question for each non-functional requirement and writing out how to perform the test in terms of user feedback.

**Comment by qureshe** [comment]
To further support the data we used task walkthroughs
