### ISSUE TITLE
Team 20 SRS Review: Missing scope of work

### ISSUE THREAD

**Issue by kelhuynh** [RutheniumVI/UnderTree#7]
Potentially missing scope. It may seem redundant in relativity to the purpose of the project and work partitioning table. However, it is important to note that the purpose defines the reason or goal for the project, whereas the scope defines the extent of what's going to be done to achieve the project specific goals. There is a differentiation between in-scope and out-of-scope bounds which could function similarly to goals and stretch goals respectively.

**Comment by kelhuynh** [comment]
You guys also may need to add a label titled "Review-SRS-Team20" and tag this issue with it

**Comment by fahmed8383** [comment]
> You guys also may need to add a label titled "Review-SRS-Team20" and tag this issue with it

Thank you for the reminder, will make sure to do so
